## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy redis server on Oracle Cloud Infrastructure Compute instances"
stackDescription: "Deploy redis server(Standalone/Master Slave(Sentinel)/Redis Cluster Architecture on Oracle Cloud Infrastructure Compute instances to take advantage of in-memory data structure store that is used as a database, cache, and message broker."
schemaVersion: 1.1.0
version: "20220422"
locale: "en"

variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - region
      - release

  - title: Required Configuration
    visible: true
    variables:
      - compartment_ocid

  - title: Networking Optional Configuration
    variables:
      - virtual_network_redis_vcn_id
      - subnet_redis_subnet_id

  - title: Advanced Configuration
    visible: true
    variables:
      - show_advanced

  - title: Redis/Sentinel Optional Configuration
    visible:
      and:
        - show_advanced
    variables:
      - redis_server
      - redis_port
      - redis_password
      - redis_prefix
      - redis_version
      - redis_deployment_type
      - redis_standalone_master_count
      - redis_masterslave_master_count
      - redis_masterslave_replica_count
      - redis_rediscluster_shard_count
      - redis_rediscluster_slave_count
      - redis_maxmemory
      - redis_port1
      - redis_port2
      - sentinel_port
      - redis_config_is_use_rdb
      - redis_config_is_use_aof
      - is_enable_backup
      - s3_bucket_name
      - s3_access_key
      - s3_secret_key

  - title: Monitoring Optional Configuration
    visible:
      and:
        - show_advanced
    variables:
      - is_use_prometheus
      - prometheus_server
      - prometheus_port
      - redis_exporter_port
      - is_use_grafana
      - grafana_server
      - grafana_port
      - grafana_user
      - grafana_password

  - title: Compute Optional Configuration
    visible:
      and:
        - show_advanced
    variables:
      - ssh_public_key
      - instance_shape
      - instance_flex_shape_ocpus
      - instance_flex_shape_memory
      - instance_os
      - linux_os_version

  - title: Tagging
    visible:
      and:
        - show_advanced
    variables:
      - tag_value

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  virtual_network_redis_vcn_id:
    type: oci:core:vcn:id
    required: true
    visibile: true
    title: "Virtual cloud network"
    description: "Choose virtual cloud network to be chosen for deploy of Redis compute instances."
    dependsOn:
      compartmentId: ${compartment_ocid}

  subnet_redis_subnet_id:
    type: oci:core:subnet:id
    required: true
    visibile: true
    title: "Subnet"
    description: "Choose subnet to be chosen for deploy of Redis compute instances."
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${virtual_network_redis_vcn_id}

  redis_server:
    type: string
    required: true
    default: ""
    title: "Redis master server hostname or IP"
    description: "Input redis master server hostname or IP to which now server will be added."

  redis_port:
    type: string
    required: true
    default: "6379"
    title: "Redis master server port"
    description: "Input redis master server port to which now server will be added."

  redis_password:
    type: password
    required: true
    default: ""
    title: "Redis master server password"
    description: "Input redis master server password to which now server will be added."

  redis_prefix:
    type: string
    required: true
    default: ""
    title: "Redis prefix"
    description: "Name the prefix for all OCI resources (compute) that will be created."

  redis_deployment_type:
    type: enum
    required: true
    title: "Redis deployment type?"
    description: "Choose redis deployment type to be deployed."
    enum:
      - "Redis Cluster"
    default: "Redis Cluster"

  redis_version:
    type: enum
    required: true
    default: "6.2.6"
    title: "Redis version"
    description: "Choose Redis version to be deployed."
    enum:
      - "5.0.14"
      - "6.0.16"
      - "6.2.6"
      - "7.0-rc3"

  redis_standalone_master_count:
    type: number
    required: true
    minimum: 1
    maximum: 1
    multipleOf: 1
    default: 1
    title: "Number of redis master node"
    description: "Choose number of redis master node."
    visible:
      and:
        - eq:
            - redis_deployment_type
            - "Standalone"

  redis_masterslave_master_count:
    type: number
    required: true
    minimum: 1
    maximum: 1
    multipleOf: 1
    default: 1
    title: "Number of redis master node"
    description: "Choose number of redis master node."
    visible:
      and:
        - eq:
            - redis_deployment_type
            - "Master Slave"

  redis_masterslave_replica_count:
    type: number
    required: true
    minimum: 2
    maximum: 2
    multipleOf: 1
    default: 2
    title: "Number of redis replicas"
    description: "Choose number of redis replicas."
    visible:
      and:
        - eq:
            - redis_deployment_type
            - "Master Slave"

  redis_rediscluster_shard_count:
    type: number
    required: true
    minimum: 1
    maximum: 1
    multipleOf: 1
    default: 1
    title: "Number of redis master nodes"
    description: "Choose number of redis master nodes."
    visible:
      and:
        - eq:
            - redis_deployment_type
            - "Redis Cluster"

  redis_rediscluster_slave_count:
    type: number
    required: true
    minimum: 0
    maximum: 2
    multipleOf: 1
    default: 1
    title: "Number of redis slaves"
    description: "Choose number of redis slaves."
    visible:
      and:
        - eq:
            - redis_deployment_type
            - "Redis Cluster"

  redis_maxmemory:
    type: number
    required: true
    minimum: 1
    multipleOf: 1
    title: "Redis maxmemory"
    description: "Input Redis maxmemory."

  redis_port1:
    type: number
    required: true
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 6379
    title: "Redis client port"
    description: "Choose Redis normal client communication port (We recommend default 6379)."

  redis_port2:
    type: number
    required: true
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 16379
    title: "Redis cluster bus port"
    description: "Choose Redis cluster bus port must be reachable from all the other cluster nodes. (We recommend default 16379)."

  sentinel_port:
    type: number
    required: true
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 26379
    title: "Redis Sentinel port"
    description: "Choose Redis Sentinel port. (We recommend default 26379)."

  redis_config_is_use_rdb:
    type: boolean
    required: true
    title: "RDB (Redis Database)?"
    description: "Choose whether to use RDB (Redis Database) to perform point-in-time snapshots."
    default: true

  redis_config_is_use_aof:
    type: boolean
    required: true
    title: "Append Only File(AOF)?"
    description: "Choose whether to use append only file(AOF) to persistence logs every write operation received by the server."
    default: false

  is_enable_backup:
    type: boolean
    required: false
    title: "Enable backup?"
    description: "Choose whether to enable hourly and daily backup."
    default: false
    visible:
      and:
        - redis_config_is_use_rdb

  s3_bucket_name:
    type: string
    required: true
    default: "RedisBucket"
    title: "S3/S3 Compatibility Bucket Name"
    description: "Name of S3/S3 Compatibility Bucket. (You must create it in advance)."
    visible:
      and:
        - is_enable_backup

  s3_access_key:
    type: string
    required: true
    default: ""
    title: "S3/S3 Compatibility Bucket access key"
    description: "S3/S3 Compatibility Bucket access key. (You must create it in advance)."
    visible:
      and:
        - is_enable_backup

  s3_secret_key:
    type: password
    required: true
    default: ""
    title: "S3/S3 Compatibility Bucket secret key"
    description: "S3/S3 Compatibility Bucket secret key. (You must create it in advance)."
    visible:
      and:
        - is_enable_backup

  is_use_prometheus:
    type: boolean
    required: false
    title: "Monitor by prometheus?"
    description: "Choose whether to use prometheus to collect metrics. (You must have an existing prometheus already)."
    default: false

  prometheus_server:
    type: string
    required: false
    default: "redismanager"
    title: "Prometheus server hostname or IP"
    description: "Input prometheus server hostname or IP."
    visible:
      and:
        - is_use_prometheus

  prometheus_port:
    type: number
    required: false
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 9091
    title: "Prometheus server port"
    description: "Input prometheus server port."
    visible:
      and:
        - is_use_prometheus

  redis_exporter_port:
    type: number
    required: false
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 9121
    title: "Redis exporter port for prometheus"
    description: "Input redis exporter port for prometheus."
    visible:
      and:
        - is_use_prometheus

  is_use_grafana:
    type: boolean
    required: false
    title: "Visualized by grafana?"
    description: "Choose whether to use grafana to visualize your metrics. (You must have an existing grafana already)."
    default: false
    visible: false

  grafana_server:
    type: string
    required: false
    default: "redismanager"
    title: "Grafana server hostname or IP"
    description: "Input grafana server hostname or IP."
    visible:
      and:
        - is_use_grafana

  grafana_port:
    type: number
    required: false
    minimum: 0
    maximum: 65535
    multipleOf: 1
    default: 3000
    title: "Grafana server port"
    description: "Input grafana server port."
    visible:
      and:
        - is_use_grafana

  grafana_user:
    type: string
    required: false
    default: "admin"
    title: "Grafana server username"
    description: "Input grafana server username."
    visible:
      and:
        - is_use_grafana

  grafana_password:
    type: password
    required: false
    default: ""
    title: "Grafana server password"
    description: "Input grafana server password."
    visible:
      and:
        - is_use_grafana

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    default: "VM.Standard.E4.Flex"
    title: "Instance shape for Redis compute instances"
    description: "Choose the shape of the VM used for Redis compute instances."
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
            - eq:
                - instance_shape
                - "VM.Standard.E4.Flex"
            - eq:
                - instance_shape
                - "VM.Standard3.Flex"

  instance_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 8
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
            - eq:
                - instance_shape
                - "VM.Standard.E4.Flex"
            - eq:
                - instance_shape
                - "VM.Standard3.Flex"

  instance_os:
    type: enum
    required: false
    default: "Oracle Linux"
    title: "Operating System"
    description: "Choose Operating system for Redis compute instances."
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    default: "7.9"
    title: "OS version"
    description: "Choose Operating system version for Redis compute instances."
    enum:
      - "7.9"
      - "7.8"

  tag_value:
    type: oci:identity:tag:value
    required: false
    title: "Tagging"
    description: "Optional tags to organize and track resources in your tenancy."

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release"

outputs:

  #  redis1_public_ip_address:
  #    title: "Redis1 Server Public IP"
  #    displayText: "Redis1 Server Public IP"
  #    type: copyableString
  #    visible: true
  #
  #  redis2_public_ip_address:
  #    title: "Redis2 Server Public IP"
  #    displayText: "Redis2 Server Public IP"
  #    type: copyableString
  #    visible: true
  #
  #  redis3_public_ip_address:
  #    title: "Redis3 Server Public IP"
  #    displayText: "Redis3 Server Public IP"
  #    type: copyableString
  #    visible: true
  #
  #  redis4_public_ip_address:
  #    title: "Redis4 Server Public IP"
  #    displayText: "Redis4 Server Public IP"
  #    type: copyableString
  #    visible: true
  #
  #  redis5_public_ip_address:
  #    title: "Redis5 Server Public IP"
  #    displayText: "Redis5 Server Public IP"
  #    type: copyableString
  #    visible: true
  #
  #  redis6_public_ip_address:
  #    title: "Redis6 Server Public IP"
  #    displayText: "Redis6 Server Public IP"
  #    type: copyableString
  #    visible: true

  redis_password:
    title: "Redis auth password"
    displayText: "Redis auth password"
    type: copyableString
    visible: true

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: copyableString
    visible: true
